---
- name: Setup database
  hosts: database
  become: yes
  roles:
    - /vagrant/roles/rojinebrahimi.wp_mysql
     
  tasks:
    - name: Configure SSH firewall
      ufw:
        rule: allow
        name: "OpenSSH"        