---
- name: Deploy Wordpress
  hosts: wordpress
  become: yes
  roles:
    - /vagrant/roles/rojinebrahimi.wp_nginx
    - /vagrant/roles/rojinebrahimi.wp_php
    - /vagrant/roles/rojinebrahimi.wordpress
    
  tasks:        
    - name: Configure SSH firewall
      ufw:
        rule: allow
        name: "OpenSSH"
      notify: 
        - Reload firewall

  handlers:
    - name: Reload firewall
      ufw:
        state: reloaded
