CREATE DATABASE IF NOT EXISTS wpDB DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE USER IF NOT EXISTS 'berna'@'192.168.50.%' IDENTIFIED BY 'Asd123';
GRANT ALL ON wpDB.* TO 'berna'@'192.168.50.%';
FLUSH PRIVILEGES;

